run:
  timeout: 5m

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - wsl

linters-settings:
  wsl:
    allow-assign-and-call: true
    allow-multiline-assign: true
    enforce-err-cuddling: false
    force-short-decl-cuddling: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
