export { registerFeature, getRegisteredFeatures, clearRegistry } from './registry.js'
export { parseDeepLink } from './deepLink.js'
export { buildInitialStack } from './stackBuilder.js'
export type { Feature, Route, NavigationItem } from './types.js'
export type { DeepLink } from './deepLink.js'
export type { BuildStackOptions } from './stackBuilder.js'
